### ISSUE TITLE
Hover Label Width

### ISSUE THREAD

**Issue by Strattonshrugged** [strattonbrazil/busyimg#14]
Add some padding, eliminate dead space on right side of tag
Tag is currently fixed width, label should wrap inside a fixed maximum

**Comment by strattonbrazil** [comment]
While investigating this they should also make sure the label remains on screen when calculating position. 

![label_cutoff](https://user-images.githubusercontent.com/786471/107157606-e15db800-6939-11eb-935a-97f331e47c93.png)
